### ISSUE TITLE
[ERROR] Script Error = Couldn't find module: com.obscure.couchbase_ti.

### ISSUE THREAD

**Issue by dump66** [pegli/couchbase_ti#6]
Hi pegli,
first i wanna thank you for your great job and hard work. I'm trying to get the module started for some days now but it just don't work. Today i tested the version 1.0.1 and used the new instructions on the wiki page. That fixed an error which i had the last days, but now Titanium says it can't find the module. In the tiapp.xml i just replaced <module/> with <module platform="iphone" version="1.0.1">com.obscure.couchbase_ti</module>. The rest i left as it was. I also created a new mobile project for testing.

Here is my console output when i start the app:

<pre>

[INFO] One moment, building ...
[DEBUG] Detecting modules in /Users/schultze/Documents/Titanium Studio Workspace/test1/modules
[DEBUG] Detecting modules in /Users/schultze/Library/Application Support/Titanium/modules
[DEBUG] Detected module for iphone: com.obscure.couchbase_ti 1.0.1 @ /Users/schultze/Library/Application Support/Titanium/modules/iphone/com.obscure.couchbase_ti/1.0.1
[INFO] Titanium SDK version: 1.7.3
[INFO] iPhone Device family: universal
[INFO] iPhone SDK version: 4.3
[INFO] iPhone simulated device: iphone
[DEBUG] executing command: /usr/bin/killall iPhone Simulator
[DEBUG] No matching processes belonging to you were found
[DEBUG] finding old log files
[DEBUG] executing command: mdfind -onlyin /Users/schultze/Library/Application Support/iPhone Simulator/4.3 -name 9fe6cb6b-e2dc-4e4b-90de-b3f0394090cb.log
[INFO] Launching application in Simulator
[INFO] Launched application in Simulator (1.31 seconds)
[DEBUG] executing command: xcodebuild -version
[DEBUG] Xcode 4.0.2
[DEBUG] Build version 4A2002a
[INFO] Found 4.3.2 patch installed
[INFO] Application started

[DEBUG] reading stylesheet from: /Users/schultze/Library/Application Support/iPhone Simulator/4.3.2/Applications/07ED2FC3-6CA4-4BC8-BC11-D56756265791/test.app/stylesheet.plist

[INFO] test1/1.0 (1.7.3.dcf4257)

[DEBUG] Analytics is enabled = YES

[DEBUG] loading: /Users/schultze/Documents/Titanium Studio Workspace/test1/Resources/app.js, resource: Users/schultze/Documents/Titanium Studio Workspace/test1/Resources/app_js

[DEBUG] loading: /Users/schultze/Documents/Titanium Studio Workspace/test1/Resources/com.obscure.couchbase_ti.js, resource: Users/schultze/Documents/Titanium Studio Workspace/test1/Resources/com_obscure_couchbase_ti_js

[ERROR] Script Error = Couldn't find module: com.obscure.couchbase_ti.

[DEBUG] application booted in 29.577971 ms

</pre>

I'm a bit confused because Titanium detects the module but later it can't find it.

Thanks in advance.

Andy

Edit: I also tried unpacking the zip as instructed in the wiki, but it makes no difference. Titanium also unpacks the zip automatically if i just put the zip into the root folder.

**Comment by orepesse** [comment]
Hi & thanks for your work !
I get the same issue:

[INFO] One moment, building ...
[DEBUG] Detecting modules in /Volumes/MAC-DOCS/Documents/Titanium Studio Workspace/couch/modules
[DEBUG] Detecting modules in /Library/Application Support/Titanium/modules
[DEBUG] Detected module for iphone: com.obscure.couchbase_ti 1.0.1 @ /Library/Application Support/Titanium/modules/iphone/com.obscure.couchbase_ti/1.0.1
[DEBUG] Looking for Titanium Module id: com.obscure.couchbase_ti, version: 1.0.1, platform: iphone
[INFO] Detected third-party module: com.obscure.couchbase_ti/1.0.1
[INFO] Titanium SDK version: 1.7.3
[INFO] iPhone Device family: universal
[INFO] iPhone SDK version: 5.0
[INFO] iPhone simulated device: iphone
[DEBUG] executing command: /usr/bin/killall iPhone Simulator
[DEBUG] No matching processes belonging to you were found
[DEBUG] finding old log files
[DEBUG] executing command: mdfind -onlyin /Volumes/MAC-DOCS/Library/Application Support/iPhone Simulator/5.0 -name e974976b-4179-4fc3-9bd1-425b6c6e691c.log
[DEBUG] /Volumes/MAC-DOCS/Library/Application Support/iPhone Simulator/5.0/Applications/5C39A156-E773-4DF4-A7B2-40F272B6D3E9/Documents/e974976b-4179-4fc3-9bd1-425b6c6e691c.log
[DEBUG] removing old log file: /Volumes/MAC-DOCS/Library/Application Support/iPhone Simulator/5.0/Applications/5C39A156-E773-4DF4-A7B2-40F272B6D3E9/Documents/e974976b-4179-4fc3-9bd1-425b6c6e691c.log
[INFO] Launching application in Simulator
[INFO] Launched application in Simulator (9.16 seconds)
[DEBUG] executing command: xcodebuild -version
[DEBUG] Xcode 4.2
[DEBUG] Build version 4C199
[INFO] Found 5.0 patch installed
[INFO] Application started

[DEBUG] reading stylesheet from: /Volumes/MAC-DOCS/Library/Application Support/iPhone Simulator/5.0/Applications/5C39A156-E773-4DF4-A7B2-40F272B6D3E9/couch.app/stylesheet.plist

[INFO] Test/1.0 (1.7.3.dcf4257)

[DEBUG] Analytics is enabled = YES

2011-10-24 16:27:32.763 couch[14344:207] Applications are expected to have a root view controller at the end of application launch

[DEBUG] loading: /Volumes/MAC-DOCS/Documents/Titanium Studio Workspace/couch/Resources/app.js, resource: Volumes/MAC-DOCS/Documents/Titanium Studio Workspace/couch/Resources/app_js

[DEBUG] loading: /Volumes/MAC-DOCS/Documents/Titanium Studio Workspace/couch/Resources/com.obscure.couchbase_ti.js, resource: Volumes/MAC-DOCS/Documents/Titanium Studio Workspace/couch/Resources/com_obscure_couchbase_ti_js

[ERROR] Script Error = Couldn't find module: com.obscure.couchbase_ti.

[DEBUG] application booted in 70.327997 ms

Module is detected but it is unable to use it

**Comment by pegli** [comment]
If you haven't done so already, can you try deleting your build directory in your test app and rebuilding from scratch?  

orepesse, I see that you have your Titanium SDK installed under /Library/Application Support/Titanium, not /Users/[your username]/Library/Application Support/Titanium.  Can you check to make sure that the latter directory does not exist?

If neither of these suggestions work, can you try downloading the CouchBooks sample app that I recently added to Github and see if that runs for you?  Thanks!

**Comment by pegli** [comment]
Also, there are numerous reports of similar issues in the Titanium Q&A database which mainly have to do with the directory where the module was installed.  See:

http://developer.appcelerator.com/question/120139/titanium-studio---modules-not-working
http://developer.appcelerator.com/question/125643/tibarcode-or-any-of-the-other-ti-plus-modules-refuse-to-work
http://developer.appcelerator.com/question/126998/how-to-change-config-to-make-modules-work-on-lion

**Comment by dump66** [comment]
Ok i hope you won't hate me now for wasting your time, but at least my problem is fixed. :-)

I compared my TiApp and yours and noticed that i just forgot the "modules" before the import of the module like in your TiApp.

Thank you for uploading the sample app so i could fix my problem and keep on doing your great job.

**Comment by orepesse** [comment]
Ok thanks a lot, I want to see couchbooks !!!!!

I get now this error is it because I have xcode 4.2 ?

[INFO] One moment, building ...
[DEBUG] Detecting modules in /Volumes/MAC-DOCS/Documents/Titanium Studio Workspace/couch/modules
[DEBUG] Detecting modules in /Library/Application Support/Titanium/modules
[DEBUG] Detected module for iphone: com.obscure.couchbase_ti 1.0.1 @ /Library/Application Support/Titanium/modules/iphone/com.obscure.couchbase_ti/1.0.1
[DEBUG] Looking for Titanium Module id: com.obscure.couchbase_ti, version: 1.0.1, platform: iphone
[INFO] Detected third-party module: com.obscure.couchbase_ti/1.0.1
[INFO] Titanium SDK version: 1.7.3
[INFO] iPhone Device family: universal
[INFO] iPhone SDK version: 5.0
[INFO] iPhone simulated device: iphone
[INFO] Compiling localization files
[DEBUG] compiled ios file: /Volumes/MAC-DOCS/Documents/Titanium Studio Workspace/couch/build/iphone/build/Debug-iphonesimulator/couch.app/en.lproj/Localizable.strings
[ERROR] 
[ERROR] Error: Traceback (most recent call last):
  File "/Library/Application Support/Titanium/mobilesdk/osx/1.7.3/iphone/builder.py", line 1148, in main
    execute_xcode("iphonesimulator%s" % link_version,["GCC_PREPROCESSOR_DEFINITIONS=**LOG__ID**=%s DEPLOYTYPE=development TI_DEVELOPMENT=1 DEBUG=1 TI_VERSION=%s %s" % (log_id,sdk_version,debugstr)],False)
  File "/Library/Application Support/Titanium/mobilesdk/osx/1.7.3/iphone/builder.py", line 1066, in execute_xcode
    output = run.run(args,False,False,o)
  File "/Library/Application Support/Titanium/mobilesdk/osx/1.7.3/iphone/run.py", line 39, in run
    sys.exit(rc)
SystemExit: 65

thanks 
Olivier

**Comment by dump66** [comment]
do you get this error when you run the simulator or deploy the app on your iphone? Because on simulator it works like a charm but when i try deploying it on iphone/ipod touch it crashes with the same error.

**Comment by orepesse** [comment]
in the simulator...

On Thu, Oct 27, 2011 at 3:29 PM, dump66 <
reply@reply.github.com>wrote:

> do you get this error when you run the simulator or deploy the app on your
> iphone? Because on simulator it works like a charm but when i try deploying
> it on iphone/ipod touch it crashes with the same error.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pegli/couchbase_ti/issues/6#issuecomment-2543345

##

**Comment by dump66** [comment]
Maybe you could switch the directory of Titanium from Library/Application Support to Users/"your username"/Library/Application Support. You can change it in the preferences of Titanium.

I hope pegli can help you more.

**Comment by orepesse** [comment]
It's what I have already done, I do not understand.
thanks

On Thu, Oct 27, 2011 at 3:44 PM, dump66 <
reply@reply.github.com>wrote:

> Maybe you could switch the directory of Titanium from Library/Application
> Support to Users/"your username"/Library/Application Support. You can change
> it in the preferences of Titanium.
> 
> I hope pegli can help you more.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pegli/couchbase_ti/issues/6#issuecomment-2543503

##

**Comment by pegli** [comment]
orepesse, when you see an "Error 65" with a build, it means that the Titanium build script failed for some reason.  That error code is not specific to the reason for the failure, however.  Open up the build/iphone/build/build.log file and scroll to the end to find out what is actually going wrong.

Because the module works in the simulator but not in a device build, I'm guessing that you're running into the same problem that I had with another commercial module very recently: the couchbase_ti module is not built for armv6.  If this is the case, you will see a linker error at the bottom of build.log that says something like "Mach-O universal binary missing armv6 slice".  I will fix this build issue and post a new module zip file later today.

**Comment by orepesse** [comment]
here my log file, I do not find what is actually going wrong.
o error like this:
"Mach-O universal binary missing armv6 slice"

Thanks !

On Thu, Oct 27, 2011 at 5:16 PM, Paul Mietz Egli <
reply@reply.github.com>wrote:

> orepesse, when you see an "Error 65" with a build, it means that the
> Titanium build script failed for some reason.  That error code is not
> specific to the reason for the failure, however.  Open up the
> build/iphone/build/build.log file and scroll to the end to find out what is
> actually going wrong.
> 
> Because the module works in the simulator but not in a device build, I'm
> guessing that you're running into the same problem that I had with another
> commercial module very recently: the couchbase_ti module is not built for
> armv6.  If this is the case, you will see a linker error at the bottom of
> build.log that says something like "Mach-O universal binary missing armv6
> slice".  I will fix this build issue and post a new module zip file later
> today.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pegli/couchbase_ti/issues/6#issuecomment-2544761

##

**Comment by pegli** [comment]
dump66, there's a new build in the download section that should fix your problem on compiling for the device.

orepresse, the log file didn't come through.  Can you paste the last 50-100 lines as text into a comment on this issue on the Github web site?

Thanks!

**Comment by dump66** [comment]
thanks pegli. unfortunately i uninstalled titanium yesterday, because i thought it could be a titanium problem. So i don't have the log anymore and can't say if i have the line at the end. I will reinstall Titanium today and tell you if the problem is fixed.

Edit: i re-installed titanium now and i can run the app in simulator and on the device. good job pegli. But there is still a problem with the app. In simulator everything works fine but on the device are no books shown. There is only the bar on top of the window with the label Books and the two buttons.

**Comment by pegli** [comment]
Yep, the books app doesn't load the source data properly yet.  That example app is still a work in progress, but at least you're seeing what I'm seeing right now.  I'll update this issue when CouchBooks is running properly on the device.

**Comment by pegli** [comment]
I've fixed the issue with CouchBooks that was causing it to fail on the device.  Let me know if you have trouble running it.

**Comment by dump66** [comment]
I started the app and it works on device. I can see the books now. But i get an error message (which disappears after some seconds on device) which says:
"Verification issue

Unlicensed module(s) detected. You must be a subscriber to use one or more of the modules included with this project."

http://developer.appcelerator.com/question/125625/unlicensed-module

Maybe it has something to do with that?

**Comment by pegli** [comment]
The "unlicensed module" message comes from the Titanium SDK, which checks the Marketplace to see if you've purchased the modules you're trying to use in a build.  I have put the couchbase_ti module up on the Marketplace for free, so perhaps you can try "buying" it from here:

  https://marketplace.appcelerator.com/apps/951

I believe the SDK uses a module GUID when it calls home to check on registration, so perhaps I can compile the module with a different GUID on Github to avoid this problem in the future.

**Comment by dump66** [comment]
it seems the problem still exists. i purchased the module from the marketplace, downloaded it, deleted the old module from titanium folder in Application Support\Titanium\modules, deleted the old project and created a new one with your sample app. But the error still appears. Any ideas what else i can do?

Update: I also assigned myself to the product (your module) now but still no success starting the app. Is there anything i maybe forgot to do? It's confusing to me because before your fix for the device it worked without error messages (i only couldn't see the books). And now the app works fine apart from the error message. i hope you can help me fix this last issue.

**Comment by joseym** [comment]
same as above.

When I build it says `Detected third-party module: com.obscure.couchbase_ti/1.0.2` but after the app builds it says `Script Error = Couldn't find module: com.obscure.couchbase_ti.`

I have the app installed in both `/Library/Application Support/Titanium/modules/` and `~/Library/Application Support/Titanium/modules/` just to bypass the different directory issues that come up from having Titanium Studio and TiDev Community (which i prefer)

thoughts?

**Comment by pegli** [comment]
I just uploaded a new version of the module which contains a different GUID than the one on the Appcelerator Marketplace.  Please try downloading that version from https://github.com/pegli/couchbase_ti/downloads and updating your tiapp.xml to read:

```
<module platform="iphone" version="1.0.3">com.obscure.couchbase_ti</module>
```

**Comment by joseym** [comment]
new issue here: https://github.com/pegli/couchbase_ti/issues/11
